export interface ADRData {
  id: string;
  title: string;
  status: 'PROPOSED' | 'ACCEPTED' | 'SUPERSEDED';
  context: string;
  decision: string;
  consequences: string;
}

export class ADRBuilder {
  /**
   * Generates a structured ADR markdown file content.
   */
  static build(data: ADRData): string {
    return `
# ADR ${data.id}: ${data.title}

- **Status**: ${data.status}
- **Date**: ${new Date().toISOString().split('T')[0]}

## Context
${data.context}

## Decision
${data.decision}

## Consequences
${data.consequences}

---
*Generated by ngxsmk-migrate ADR Engine*
`;
  }
}