import fs from 'fs-extra';
import { ModernizationMetrics } from '../insights/modernization-score.js';

export class MarkdownExporter {
  /**
   * Generates a premium Markdown report from migration results.
   */
  static async export(path: string, metrics: ModernizationMetrics, changes: string[]) {
    const report = `
# Angular Modernization Report
Generated by **ngxsmk-migrate**

## 📊 Modernization Score: ${metrics.overallScore}/100
- **Standalone Coverage**: ${metrics.standaloneCoverage}%
- **Signals Adoption**: ${metrics.signalsAdoption}%
- **Deprecated APIs**: ${metrics.deprecatedApiCount} found

## 🛠️ Migration Summary
${changes.map(c => `- ${c}`).join('\n')}

## 🚀 Impact Analysis
This migration has improved project stability and reduced architectural technical debt by approximately **${Math.round(metrics.overallScore * 0.5)}%**.

---
*Safe. Autonomous. Enterprise Grade.*
`;

    await fs.writeFile(path, report);
  }
}